Make a separate filtering operation

diff --git a/kubeflow/components/filter-paraphrase.yaml b/kubeflow/components/filter-paraphrase.yaml
--- a/kubeflow/components/filter-paraphrase.yaml
+++ b/kubeflow/components/filter-paraphrase.yaml
@@ -1,6 +1,6 @@
-name: Paraphrase
+name: Filter Paraphrases
 description: |
-  Automatic paraphrasing of a dataset
+  Filter paraphrases using a parser
 inputs:
   - {name: image, description: '', default: ''}
   - {name: s3_bucket, description: '', default: ''}
@@ -12,8 +12,6 @@ inputs:
   - {name: s3_input_datadir, description: '', default: ''}
   - {name: filtering_model, description: '', default: ''}
   - {name: paraphrasing_model, description: '', default: ''}
-  - {name: skip_generation, description: '', default: ''}
-  - {name: skip_filtering, description: '', default: ''}
   - {name: keep_original_duplicates, description: '', default: ''}
   - {name: ignore_context, description: '', default: ''}
   - {name: paraphrase_subfolder, description: '', default: ''}
@@ -29,7 +27,7 @@ implementation:
     - |
       . /opt/genie-toolkit/lib.sh
 
-      parse_args "$0" "image s3_bucket owner task_name project experiment dataset s3_input_datadir s3_output_datadir filtering_model paraphrasing_model skip_generation skip_filtering keep_original_duplicates task_name ignore_context paraphrase_subfolder" "$@"
+      parse_args "$0" "image s3_bucket owner task_name project experiment dataset s3_input_datadir s3_output_datadir filtering_model paraphrasing_model keep_original_duplicates task_name ignore_context paraphrase_subfolder" "$@"
       shift $n
       
       set -e
@@ -48,7 +46,7 @@ implementation:
       mkdir -p output_dataset
       cp -r input_dataset/* output_dataset
       
-      s3_output_dir="s3://${s3_bucket}/${owner}/dataset/${project}/${experiment}/${dataset}-gen/`date +%s`/"
+      s3_output_dir="$s3_input_datadir" # filtering does not create a new folder
             
       mkdir -p `dirname $s3_output_datadir`
       echo ${s3_output_dir} > $s3_output_datadir
@@ -68,79 +66,6 @@ implementation:
       else
         exit 1
       fi
-
-      make_input_ready() {
-          if [ "$keep_original_duplicates" = false ] ; then
-            # remove duplicates before paraphrasing to avoid wasting effort
-            python3 /opt/genienlp/genienlp/paraphrase/scripts/transform_dataset.py \
-              ${input_dir}/train.tsv \
-              ${input_dir}/train_no_duplicate.tsv \
-              --remove_duplicates \
-              --task ${task_name}
-              cp ${input_dir}/train_no_duplicate.tsv ${input_dir}/train.tsv
-          fi
-
-          if [ "$is_dialogue" = true ] ; then
-            # add previous agent utterance; this additional context helps the paraphraser
-            python3 /opt/genienlp/genienlp/paraphrase/scripts/dialog_to_tsv.py \
-              ${input_dir}/train.tsv \
-              --dialog_file input_dataset/synthetic.txt \
-              ${output_dir}/with_context.tsv
-          else
-            : # nothing to be done
-          fi
-      }
-
-      run_paraphrase() {
-        echo $paraphrasing_arguments
-        # run paraphrase generation
-        if [ "$is_dialogue" = true ] ; then
-          if [ "$ignore_context" = true ] ; then
-            genienlp run-paraphrase \
-            --task paraphrase \
-            --model_name_or_path paraphraser \
-            --input_file ${output_dir}/with_context.tsv \
-            --output_file ${output_dir}/paraphrased.tsv \
-            --input_column 3 \
-            --thingtalk_column 2 \
-            --gold_column 3 \
-            $paraphrasing_arguments
-          else
-            genienlp run-paraphrase \
-            --task paraphrase \
-            --model_name_or_path paraphraser \
-            --input_file ${output_dir}/with_context.tsv \
-            --output_file ${output_dir}/paraphrased.tsv \
-            --input_column 0 \
-            --prompt_column 1 \
-            --thingtalk_column 2 \
-            --gold_column 3 \
-            $paraphrasing_arguments
-          fi
-        else
-          genienlp run-paraphrase \
-            --task paraphrase \
-            --model_name_or_path paraphraser \
-            --input_file ${input_dir}/train.tsv \
-            --output_file ${output_dir}/paraphrased.tsv \
-            --input_column 1 \
-            --thingtalk_column 2 \
-            $paraphrasing_arguments
-        fi
-      }
-
-      join() {
-        # join the original file and the paraphrasing output
-        export num_new_queries=$((`wc -l ${output_dir}/paraphrased.tsv | cut -d " " -f1` / `wc -l ${input_dir}/train.tsv | cut -d " " -f1`))
-        python3 /opt/genienlp/genienlp/paraphrase/scripts/transform_dataset.py \
-          ${input_dir}/train.tsv \
-          ${output_dir}/unfiltered.tsv \
-          --query_file ${output_dir}/paraphrased.tsv \
-          --num_new_queries ${num_new_queries} \
-          --transformation replace_queries \
-          --remove_with_heuristics \
-          --task ${task_name}
-      }
 
       run_parser() {
         # get parser output for paraphrased utterances
@@ -185,35 +110,14 @@ implementation:
         cat ${output_dir}/filtered.tsv >> ${output_dir}/train.tsv
       }
 
-
-      if [ "$skip_generation" = true ] ; then
-        echo "Skipping generation. Will filter the existing generations."
-        if ! test -f ${input_dir}/unfiltered.tsv ; then
-          exit 1
-        fi
-      else
-        make_input_ready
-        run_paraphrase
-        join
-
-        # paraphrasing was successful, so upload the intermediate files
-        aws s3 sync --no-progress output_dataset/ "${s3_output_dir}"
-        echo "Uploaded intermediate files to s3."
-        if test -f output_dataset/synthetic.txt ; then
-          echo "Deleting synthetic.txt from pod to save disk space..."
-          rm output_dataset/synthetic.txt
-        fi
-
+     
+      if ! test -f ${input_dir}/unfiltered.tsv ; then
+        echo "Error: unfiltered.tsv does not exist."
+        exit 1
       fi
 
-      if [ "$skip_filtering" = true ] ; then
-        echo "Skipping filtering."
-        cp ${output_dir}/unfiltered.tsv ${output_dir}/filtered.tsv
-      else
-        run_parser
-        filter
-      fi
-
+      run_parser
+      filter
       append_to_original
       
       # upload the new dataset to S3
@@ -232,8 +136,6 @@ implementation:
       --s3_output_datadir, {outputPath: s3_output_datadir},
       --filtering_model, {inputValue: filtering_model},
       --paraphrasing_model, {inputValue: paraphrasing_model},
-      --skip_generation, {inputValue: skip_generation},
-      --skip_filtering, {inputValue: skip_filtering},
       --keep_original_duplicates, {inputValue: keep_original_duplicates},
       --ignore_context, {inputValue: ignore_context},
       --paraphrase_subfolder, {inputValue: paraphrase_subfolder},
