Change if statement to case

diff --git a/kubeflow/components/filter-paraphrase.yaml b/kubeflow/components/filter-paraphrase.yaml
--- a/kubeflow/components/filter-paraphrase.yaml
+++ b/kubeflow/components/filter-paraphrase.yaml
@@ -44,25 +44,33 @@ implementation:
       echo ${s3_output_dir} > $s3_output_datadir
 
       paraphrasing_arguments="$@"
-      if "$task_name" | grep -q "almond_dialogue_nlu" ; then # almond_dialogue_nlu or almond_dialogue_nlu_agent
-        is_dialogue=true
-        input_dir="input_dataset/$paraphrase_subfolder"
-        output_dir="output_dataset/$paraphrase_subfolder"
-        filtering_dir="almond/$paraphrase_subfolder"
-        filtering_batch_size="4000"
-      elif [ "$task_name" = "almond" ] ; then
-        input_dir="input_dataset"
-        output_dir="output_dataset"
-        filtering_dir="almond"
-        filtering_batch_size="4000"
-      else
-        exit 1
-      fi
+
+      case "$task_name" in
+        "almond_dialogue_nlu" | "almond_dialogue_nlu_agent")
+          is_dialogue=true
+          input_dir="input_dataset/$paraphrase_subfolder"
+          output_dir="output_dataset/$paraphrase_subfolder"
+          filtering_dir="almond/$paraphrase_subfolder"
+          filtering_batch_size="4000"
+          ;;
+
+        "almond")
+          input_dir="input_dataset"
+          output_dir="output_dataset"
+          filtering_dir="almond"
+          filtering_batch_size="4000"
+          ;;
+
+        *)
+          echo "Error: invalid task name."
+          exit 1
+          ;;
+      esac
 
       run_parser() {
         # get parser output for paraphrased utterances
         mkdir -p filtering_dataset/${filtering_dir}
-        cp ${input_dir}/unfiltered.tsv filtering_dataset/${filtering_dir}/eval.tsv
+        cp ${output_dir}/unfiltered.tsv filtering_dataset/${filtering_dir}/eval.tsv
         genienlp predict \
           --data ./filtering_dataset \
           --path filtering_model \
@@ -81,7 +89,7 @@ implementation:
       filter() {
         # remove paraphrases that do not preserve the meaning according to the parser
         genienlp transform-dataset \
-          ${input_dir}/unfiltered.tsv \
+          ${output_dir}/unfiltered.tsv \
           ${output_dir}/filtered.tsv \
           --thrown_away ${output_dir}/thrown_away.tsv \
           --thingtalk_gold_file eval_dir/valid/${task_name}.tsv \
diff --git a/kubeflow/components/generate-paraphrase.yaml b/kubeflow/components/generate-paraphrase.yaml
--- a/kubeflow/components/generate-paraphrase.yaml
+++ b/kubeflow/components/generate-paraphrase.yaml
@@ -50,16 +50,24 @@ implementation:
       echo ${s3_output_dir} > $s3_output_datadir
 
       paraphrasing_arguments="$@"
-      if "$task_name" | grep -q "almond_dialogue_nlu" ; then # almond_dialogue_nlu or almond_dialogue_nlu_agent
-        is_dialogue=true
-        input_dir="input_dataset/$paraphrase_subfolder"
-        output_dir="output_dataset/$paraphrase_subfolder"
-      elif [ "$task_name" = "almond" ] ; then
-        input_dir="input_dataset"
-        output_dir="output_dataset"
-      else
-        exit 1
-      fi
+
+      case "$task_name" in
+        "almond_dialogue_nlu" | "almond_dialogue_nlu_agent")
+          is_dialogue=true
+          input_dir="input_dataset/$paraphrase_subfolder"
+          output_dir="output_dataset/$paraphrase_subfolder"
+          ;;
+
+        "almond")
+          input_dir="input_dataset"
+          output_dir="output_dataset"
+          ;;
+
+        *)
+          echo "Error: invalid task name."
+          exit 1
+          ;;
+      esac
 
       make_input_ready() {
           if [ "$keep_original_duplicates" = false ] ; then
