Fix syntax in yaml files

diff --git a/kubeflow/components/sts-paraphrase.yaml b/kubeflow/components/sts-paraphrase.yaml
--- a/kubeflow/components/sts-paraphrase.yaml
+++ b/kubeflow/components/sts-paraphrase.yaml
@@ -78,7 +78,8 @@ implementation:
               all_names="${input_splits_array[*]}" experiment=${experiment} skip_translation=false pivot_lang=${pivot_lang} paraphrase_gt_quoted_${tgt_lang}
           ;;
           *)
-            echo "Not a valid option"
+            echo "invalid ${nmt}+${paraphrasing_method} combo is provided"
+            exit 1
           ;;
           esac
       fi
diff --git a/kubeflow/components/translate.yaml b/kubeflow/components/translate.yaml
--- a/kubeflow/components/translate.yaml
+++ b/kubeflow/components/translate.yaml
@@ -86,7 +86,8 @@ implementation:
             make -B -j2 geniedir=/opt/genie-toolkit all_names="${input_splits_array[*]}" experiment=${experiment} gt_project_id="multilanguage-273819" gt_project_number="211743822806" gt_credential_file="gt-json/multilanguage-a40fe9320f88.json" train_output_per_example=${train_output_per_example} skip_translation=false ${experiment}/gt/${tgt_lang}/unquoted-qpis-direct-translated
           ;;
           *)
-            echo "Not a valid nmt model"
+            echo "invalid ${nmt}+${do_alignment} combo is provided"
+            exit 1
           ;;
           esac
 
